# Generated by Django 4.2.1 on 2023-05-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentasapp', '0003_alter_anuncio_deleted_at_alter_anuncio_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='deleted_at',
            new_name='deleted',
        ),
    ]
