# Generated by Django 4.2.1 on 2023-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentasapp', '0004_rename_deleted_at_anuncio_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(default=True, upload_to='anuncios'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
