# Generated by Django 4.2.1 on 2023-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentasapp', '0005_rename_user_id_anuncio_user_anuncio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(upload_to='anuncios'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
