# Generated by Django 4.2.1 on 2023-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentasapp', '0006_alter_anuncio_image_alter_anuncio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(upload_to='images/anuncios'),
        ),
    ]
