# Generated by Django 4.2.1 on 2023-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentasapp', '0007_alter_anuncio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(upload_to='anuncios'),
        ),
    ]
